# Arbeidskrav 4: Studiedesign


## Innleiing

I denne rapporten har det blitt vald ut fem forskjellige studiar som ser på effekten av blokkperiodisering opp i mot effekten av tradisjonell periodisering: @rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022 og @breil2010. Målet med denne rapporten er å analysere studiane, samt å sjå nærmare på dei statistiske analysane og val av studiedesign i studiane. Vidare skal ein vurdere styrkane og svakhetane til studien og avslutningsvis komme med råd om korleis ein skal utforme framtidige studiar for å få betre svar på korleis ein betre kan periodisere treninga. 

Alle studiane ser på eit felles spørsmål innan treningsplanlegging, nemleg korleis ein på best mogleg måte kan periodisere treninga for å få best mogleg resultat. Desse studiane ser meir konkret på korleis effekten av blokklegging av uthaldstrening (BP) står i forhold til tradisjonell periodisering av uthaldstrening (TP). Dei forskjellige studiane ser på ein del ulike faktorar blant anna laktatterskel, submaksimal og maksimal aerob effekt, maksimalt oksygenopptak (VO$_{2maks}$), hemoglobinmasse (HB$_{mass}$) og prestasjonstestar i ulike lengder og formål. Ein studie har i tillegg gjennomført ein muskulær analyse av deltakarane @almquist2022. Denne rapporten vil derimot fokusere korleis ein kan på best mogleg måte stimulere til høg VO$_{2maks}$ ved hjelp av BP opp i mot TP.


## Teori

Både lavintensitetstrening (LIT) og høgintensitetstrening (HIT) har vist å ha ein positiv effekt på VO$_{2maks}$ (@helgerud2001; @helgerud2007; @ingham2008), men fleire studiar indikera at HIT aukar den aerobe kapasiteten, målt i VO$_{2maks}$, meir effektivt enn LIT for sedentære og lavt aktive personar (@helgerud2007, laursen2002). Auka submaksimal treningsvolum slik som LIT-trening har vist seg å gjere lite for å auke VO$_{2maks}$ for godt trente utøvarar (@londeree1997), men studiar har vist at trening på eller nærme VO$_{2maks}$ er eit effektivt stimuli for å auke VO$_{2maks}$ for sjølv godt trente utøvarar (@laursen2002, @londeree1997, @midgley2006).

Blokkperiodisering (BP) er ein populær metode å organisere treninga på som oppstod på 1970-talet og har sidan stadig fått auka vitskapelig fokus og støtte for sin effektivitet (@issurin2010). Tradisjonell periodisering av uthaldstrening har vore definert som to økter med høgintensitetstrening (HIT) i veka med lavintensitetstrening fordelt vidare utover veka (@rønnestad2012). Det som definera BP er at ein prioritera utvikling av spesifikke eigenskapar i blokker for å unngå at ein får motstridande stimuli i same periode, som ein kan få i TP @issurin2018. Blokkene kan vare mellom 1-4 veker der fokuset kan til dømes vere å auke VO$_{2maks}$, i tillegg blir treninga supplert med trening som har som mål å vedlikehalde dei andre eigenskapane utan at det går utover hovudprioriteten. I tillegg vil ein at eit auka stimuli på ein eigenskap vil skape eit adekvat stimuli for å få ein betre adaptasjon av treninga for godt trena utøvarar, noko ein ikkje får til i TP med eit breidt fokus på eigenskapar over same periode (@issurin2010).

Ut i frå dette har fire av desse fem studiane utforma ei hypotese som forventar at BP vil ha overlegen effekt på forskjellige variablar, men der VO$_{2maks}$ er inkludert som ein variabel ein forventar overlegen auking i. Den siste studien frå Almquist et al. (2022) skil seg ut ved at den ikkje nemner ei hypotese i innleiinga, men riggar studien på same måte med å samanlikne BP med TP. Logikken bak BP som den overlegne treningsstrukturen er god, men fortsatt berre teoretisk. Desse studiane tar fatt på spørsmålet om kva som faktisk er den beste treningsstrukturen i praksis med dei usikkerhetane som er når ein gjennomfører slike studiar. Forskjell i element som treningsnivå og treningsrespons blant utøvarane kan vere slike faktorar som påverkar resultatet. Det kan tenkast at utgangspunktet til alle deltakarane på desse studiane er ulikt og enkelte har eit stort potensial for auking i VO$_{2maks}$ til tross for eit høvelig nivå, mens andre er mykje nærmare det genetiske taket for VO$_{2maks}$ allereie før studien starta. 

### VO$_{2maks}$

I dei studiane ein tar utgangspunkt i denne rapporten ønsker forskarane og sjå på betring i aerob og anaerob kapasitet. Som nemnt tidligare vil denne rapporten berre sjå på betring i aerob kapasitet målt i VO$_{2maks}$. VO$_{2maks}$ er den høgaste hastigheten ein kan oppnå på den aerobe energiomsetninga (@åstrand2003), og er dermed ein av dei mest avgjerande faktorane for uthaldsprestasjon. Som tidligare nemnt er både LIT, MIT og HIT vist å forbetre VO$_{2maks}$ (@helgerud2001; @helgerud2007; @ingham2008). For å forbetre VO$_{2maks}$ må ein tilføre kroppen eit stort nok treningsstimuli i form av varighet, hyppighet, intensitet og ikkje minst genetikk (@shephard1968; @wenger1986). Når uthaldsnivået til ein viss person aukar opp på eit høgt nivå viser forskinga at ein må auke intensiteten på treninga for å kunne få ei auking i VO$_{2maks}$ (@laursen2002). 

### Studiedesign

Studiane som har blitt vald ut er alle randomiserte kontrollerte studier (RCT), som vil sei at I deltakarane blir delt inn i grupper tilfeldig. I desse studiane vart ein delt inn i to forskjellige grupper: intervensjonsgruppa, med treningsstrukturen BP, og kontrollgruppa, med treningsstrukturen TP. Med randomisering kan man oppnå ei rettferdig samanlikning mellom eksponerte individ (intervensjonsgruppa) og ikkje-eksponerte individ (kontrollgruppa) (@hulley2013). Dei eventuelle ulikskapane som kjem av randomiseringa vil skuldast tilfeldighetar og ikkje systematiske forskjellar. Hensikta med ei kontrollgruppe er at ein kan samanlikne resultata med dei som har blitt eksponert med dei som ikkje er eksponert. I desse studiane vil det vere særs viktig å sjå på korleis treninga har blitt gjennomført på TP-gruppa. Dette er på grunn av at uansett korleis ein strukturera trening så vil trening føre til auka VO$_{2maks}$ om ein samanliknar med ei kontrollgruppe som ikkje trenar. Dermed må dei ikkje-eksponerte (TP) ha eit strukturert treningsopplegg som gjer det samanliknbart med dei eksponerte (BP).

Alle studiane gjennomførte ein pre-test der blant anna VO$_{2maks}$ vart testa. Dette sikrar ein for at det er store forskjellar mellom gruppene i VO$_{2maks}$ og utgangspunktet blir relativt likt. To av studiane (@rønnestad2014a; @rønnestad2014b) er basert på same forskingsprosjekt med same deltakarar og forskarar, men varigheten er forskjellig på studiane med fire (@rønnestad2014a) og tolv veker (rønnestad2014b). 

Studiane har ein del ulikskapar. I studien til Breil et al (2010) er det ikkje tatt omsyn til TP gruppa i større grad enn at dei skal gjennomføre uthald-og styrketrening som er antatt vanleg i den treningsperioden deltakarane var i. All trening vart derimot loggført og treningsbelastninga vart rekna ut i form av følt belastning (1-10) multiplisert med total treningstid i minutt, ut i frå modellen til Foster (@foster2001). I dei andre studiane er treninga til TP nøye kontrollert og kalkulert for at treningsbelastninga skal bli lik. Dette for å unngå at ein potensiell auking i VO$_{2maks}$ ikkje er på grunn av auka treningsbelastning, men på grunn av treningsstrukturen. I tillegg sikrar ein at forskjellen mellom gruppene blir stor nok til å få svar. I studiane er treningsvolumet i LIT og HIT likt, men også tal økter med LIT og HIT.

I alle studiane er det gjennomført ein pre-test i forkant av treningsintervensjonen og ein post-test etter. Det vart gjennomført litt ulike typar testar på dei ulike studiane. Alle studiane gjennomførte VO$_{2maks}$, laktatprofil, maksimal aerob effekt (W$_{maks}$) og prestasjonstestar. Rønnestad et al. sine studiar (2014a; 2014b; 2016) og Almquist et al. (2022) gjennomførte hemoglobinmasse-test, mens Almquist gjennomførte i tillegg ein muskelbiopsi.  Som tidligare nemnt så fokusere ein berre på VO$_{2maks}$ i denne studien. Alle dei fysiske testane vart gjennomført i same rørsleform som HIT-øktene, i tillegg med MIT øktene i @almquist2022 sin studie.

### Deltakarar og rekruttering

I studien til @breil2010 var det totalt 15 menn og 6 kvinner som deltok på studien, alle definert som eliteutøvarar innan alpint. @almquist2022 hadde fire kvinner og 26 menn fordelt på to teststasjonar, 15 på kvar, alle definert som trente syklistar. @rønnestad2016 hadde 14 menn og 5 kvinner som deltok på studien, som var klassifisert som eliteutøvarar. Sjølv om studien var spesifikt retta mot langrenn var det eit uvisst tal skiskyttarar som deltok som forsøkspersonar, men dei gjennomførte den same treninga som dei andre under intervensjonen. @rønnestad2014a var det 19 menn som fullførte treningsintervensjonen, der alle var klassifisert som godt trena syklistar. Som tidligare nemn var det dei same deltakarane som deltok i @rønnestad2014b, men her var det berre 15 som fullførte heile treningsintervensjonen på 12 veker.

Alle deltakarane signerte på førehand eit samtykke om deltakinga på studien, og dei vart informert på førehand om potensielle risikofaktorar. Studiane til @rønnestad2014a, @rønnestad2014b, @rønnestad2016 og @almquist2022 vart godkjend av den lokale etiske komité på Lillehammer. @breil2010 vart godkjend hos den etiske komiteen i Bern, Sveits. I denne studien måtte også deltakarane gjennomføre ein EKG og dei måtte bekrefte at dei ikkje hadde hjarte- og lungesjukdom. Alle studiane vart gjennomført etter Helsinki-erklæringa. Ingen av studiane har grunngjeve deltakarstørrelsen, og ingen har gjennomført kalkuleringar for å teste kor mange deltakarar det hadde vore gunstig å inkludere i studiane.

### Treningsintervensjon 

Treningsintervensjonen i desse studiane varierte stort i frå 11 dagar til 12 veker. Studien som skil seg mest ut er @breil2010 som gjennomførte ein treningsintervensjon med totalt 15 HIT-økter fordelt på 11 dagar. Intervensjonen var periodisert i ein mikrosyklus med eit 2-1-2 mønster i tal HIT-økter per dag, etterfulgt av ein kviledag. Det var totalt 3 mikrosyklusar. 12 av HIT-øktene var gjennomført på ergometer sykkel, mens den siste økta i kvar syklus vart gjennomført i ei hinderløype som var spesifikk til alpin. Alle HIT-øktene vart gjennomført som 4 x 4 min intervall med 3 min aktiv pause. Intensiteten vart justert etter den personlige maksimale pulsen (HR$_{maks}$) og følt belastning etter borgs skala (6-20). TP-gruppa vart instruert til å trene som normalt for perioden intervensjonen vart gjennomført. 

Studiane til Rønnestad (2014a; 2014b) og Almquist (2022) inkludera ein tredeling av intensitetsstyring med LIT, MIT og HIT. @rønnestad2016 brukar berre ein polarisert modell med LIT og HIT. Rønnestad definera LIT som 60-82% av HR$_{maks}$, MIT som 83-87% av HR$_{maks}$ og HIT som 88-100% av HR$_{maks}$. Almquist definera ikkje intensitetssonene, men nemner at eit mål med kvar intervalløkt var å auke opplevd belastning gjennom økta. MIT som 14-18 og HIT som 16-19 på borgs skala. 

@rønnestad2016 gjennomførte ein intervensjon på 5 veker. BP gjennomførte  med ein stor HIT-blokk på veke 1 med 5 HIT-økter og ein moderat HIT-blokk på veke 3 med 3 HIT-økter. Veke 2, 4 og 5 vart gjennomført med 1 HIT-økt i veka. Resten av treningsvolumet vart gjennomført som LIT. TP Gjennomførte 2 HIT-økter i veke 1, 2, 4 og 5. I veke 3 gjennomførte dei same treningsopplegget som BP. HIT-øktene vart gjennomført annakvar 5 x 6 min og 6 x 5 min med 2,5 til 3 min pause. Deltakarane vart instruert til å gjennomføre minimun 50% av HIT-øktene i stilarten skøyting enten på rulleski eller på ski.

I @rønnestad2014a gjennomførte BP ein HIT-blokk med 5 HIT-økter i veka og dei resterande 3 vekene med 1 HIT-økt i veka og større LIT-volum. TP gjennomførte 2 HIT-økter i veka, med eit jamt høgt nivå med LIT fordelt mellom HIT-øktene. Dette vart også gjennomført i 4 veker. Det vart gjennomført eit like stort volum på HIT og LIT i begge gruppene. HIT-øktene vart gjennomført annakvar 5 x 6 min og 6 x 5 min med 2,5 til 3 min pause på begge gruppene. @rønnestad2014b gjennomførte det same treningsopplegget totalt 3 gonger for å få 3 syklusar på 4 veker. 

@almquist2022 er den einaste av desse studiane som inkludera MIT i treningsopplegget. Treningsregimet var lagt opp i tre mesosyklusar på 4 veker kvar. For BP gruppa bestod kvar mesosyklus av 4 MIT-økter i veke 1, tre LIT-økter i veke 2 og fire HIT-økter i veke 3. For TP-gruppa var LIT, MIT og HIT øktene fordelt jamt ut over desse 3 vekene. Felles for begge gruppene var at veke 4 var satt av som restitusjonsveke. Treningsøktene var satt opp slik at for BP var HIT-øktene var 5 x 5 min med progressiv intensitet, og MIT-øktene var 4 x 12 min med progressiv intensitet. Deltakarane vart instruert i å ha eit høgast mogleg gjennomsnittswatt gjennom økta, men intensiteten skulle vere progressiv. TP gruppa hadde ein progressiv tilnærming til intervalløktene med auke i tal drag for kvar mesosyklus. Dette tilseier 4, 5 og 6 drag på 5 min på HIT-øktene og 3, 4 og 5 drag på 12 min på MIT-øktene på dei ulike syklusane. Totalt vart treningsvolumet likt både på LIT, MIT og HIT.

### Statistiske analysar

Alle studiane baserar seg på eit RCT-studiedesign og dette blir gjenspegla i val av statistiske analysar. Alle studiane vel å presentere resultata som gjennomsnitt ± standardavvik (SD). Sidan ein skal samanlikne to grupper og seinare den eventuelle progresjonen i to grupper nyttar ein ulike verktøy for å presentere forskjellane. Dei ulike verktøya som vart brukt varierte noko. @rønnestad2014a, @rønnestad2014b og @rønnestad2016 brukte Cohens d for å rekne ut effektstørrelsen (ES) for å sjå etter statistisk signifikans. Kriteria som vart satt for å tolke ES var følgande: 0.0--0.2 triviell, 0.2--0.6 liten, 0.6--1.2 moderat, 1.2--2.0 stor, og >2.0 veldig stor (@hopkins2009). Grunnen til dette er for at det skal bli lettare å sjå omfanget av resultata, i motsetning til statistisk signifikans som ser på om resultata skjer på grunn av tilfeldighetar. 

@almquist2022 nyttar ein blanda lineær modell med grupper definert som «fixed effects» og korregert ved hjelp av pre-verdiar som ein kovarians med software SPSS v.25. @breil2010 rekna ut forskjellen mellom gruppane ved hjelp av ein to-hala t-test for uparra testar, mens for å sjå på endringane mellom deltakarane frå pre- til post-test vart det brukt to-hala t-test for parra testar. ANOVA vart nytta for å samanlikne forskjellar mellom grupper og kjønn på to faktorar (intervensjon x tid). ANOVA vart også nytta i @rønnestad2014a, @rønnestad2014b, @rønnestad2016, men i ulik grad. I nokre studiar vart ein to-veis repeterande analyse av varians nytta for å evaluere differansen innad og mellom gruppene frå pre- til post-test. I @rønnestad2014a og @rønnestad2014b vart uparra t-testar nytta for å samanlikne gruppene ved baseline og gruppene sine respektive treningsvolum. Samtidig vart pre- til post-test samanlikna ved hjelp av parra t-testar, og for å teste forskjellane mellom gruppene vart uparra t-testar nytta.

I alle studiane er det nytta statistiske verktøy for å samanlikne gruppene både innad i gruppa og mellom gruppene. Forskjellen mellom gruppene må ein samanlikne for å kunne gje eit svar på kva treningsprotokoll som gjev den beste treningsresponsen. Grunnen til at ein ynskjer å samanlikne innad i gruppa i slike studiar er at ein kan vurdere effekten av intervensjonen på individnivå noko som kan hjelpe med å sjå korleis deltakarane endrar seg over intervensjonen. Eventuelle endringar som observerast innad i gruppa kan indikere at faktorar som utanfor behandlinga påverkar utfallet. I slike studiar kan dette indikere overbelastning, sjukdom eller andre faktorar som påverkar prestasjon og trening.

## Resultat

I fire av desse fem studiane vart det signifikant auke i den relative VO$_{2maks}$ for BP-gruppene, mens det ikkje vart registrert auke blant TP-gruppene. ES av den relative forbetringa viser moderat til høg effekt av BP samanlikna med TP (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @breil2010).

@almquist2022 gjennomførte VO$_{2maks}$ både etter veke 4 og veke 12 og fikk ingen endring i VO$_{2maks}$ i nokon av gruppene.

Hypotesen vart testa og viste seg korrekt i fire av fem studiar. BP ser dermed ut som ein effektiv treningsstruktur for å auke VO$_{2maks}$ samanlikna med TP. 

## Diskusjon

Denne rapporten viser at i fire av fem utvalse studiar viser BP seg som ein overlegen treningsstruktur samanlikna med TP for å auke VO$_{2maks}$. Studiane skil seg på fleire måtar, men i varigheten strakk dei seg frå 11 dagar til 12 veker. Studien til @almquist2022 skil seg ut med at den ikkje bekreftar hypotesa om at BP er ein betre treningsstruktur for å auke VO$_{2maks}$. @almquist2022 skil seg også ut med at det er den einaste studien som inkludera MIT i treningsintervensjonen, noko den hevdar å vere ein av dei fyrste studiane som inkludera denne intensiteten i ein slik samanlikning mellom BP og TP (@almquist2022). 

Alle studiane, utanom @breil2010, justerte treningsintervensjonen til TP slik at den totale treningsbelastning vart lik. Treningsvolum, tid i ulike soner og tal hardøkter var lik både i TP og BP. Dette er ein stor styrke for desse studiane: @rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022. Grunnen til at dette er så viktig er at dette går til kjernen av problemet, nemleg treningsstruktur. Den totale treninga er lik, men rekkjefølga er ulik. 

@breil2010 skil seg ganske kraftig ut i med tanke på treningsintervensjonen til TP. TP-gruppa vart instruert til å trene som normalt for perioden der treningsintervensjonen vart gjennomført. Det er ikkje nemnt noko om ein strukturert treningsplan for denne gruppa for å få ein så lik total treningsbelastning som mogleg. Alt av trening blir registrert for begge gruppene og treningsbelastninga blir rekna ut som følt belastning (1-10) multiplisert med total treningstid i minutt. @breil2010 skriv at treningsbelastninga er lik for gruppene der BP 6,328 ± 1,388 og for TP 8,119 ± 2,812, dette fordi til tross for auka følt belastning er det totale treningsvolumet i timar (h) stor mellom gruppene: BP med 13.9 ± 2.7 h og TP med 23.9 ± 5.6 h. Dette er ikkje ein ubetydelig forskjell i treningsbelastning og gjer det vanskeleg å sjå om det er den auka intensiteten i treninga som gjev utslaget eller om det er treningsstrukturen som gjev utslaget. 

Tilsyn på treningsøktene under treningsintervensjonen er noko som skil seg mellom studiane. @breil2010 gjennomførte alle HIT-øktene under oppsyn av testleiar. I studien til @almquist2022 var det påkravd at fire av hardøktene skulle bli gjennomført med oppsyn av testleiar, for å sikre at deltakarane forstod kva som var kravd av dei og korleis øktene skulle bli gjennomført. Deltakarane hadde også moglegheita til å gjennomføre alle HIT- og MIT-øktene på denne måten, men det står ikkje skreve om kor mange av dei som nytta seg av tilbodet. @rønnestad2014a og @rønnestad2014b kontrollerte HIT-øktene ved å få innsyn i kraftutviklinga gjennom øktene ved hjelp av ein Powertap SL 2.4 (CycleOps, Madison, WI, USA), i tillegg til at deltakarane registrerte opplevd belastning. 

@almquist2022 skil seg ut som den einaste studien som inkludera MIT i treningsopplegget både til TP og BP. Almquist et al. argumentera med at til tross for at HIT har vist seg å vere meir effektiv for å auke VO$_{2maks}$ enn MIT så er MIT ein naturleg del av ein godt designa treningsplan. Det er også dermed veldig interessant at dette er den einaste studien av desse fem som ikkje får auke i VO$_{2maks}$. Dette kan ha ulik forklaring, men det er eit interessant poeng som ein må forske vidare på, særleg når ein ser at det store fleirtalet av profesjonelle uthaldsutøvarar gjennomfører MIT-trening som ein viktig del av treningsarbeidet.

Ein stor svakhet ved desse studiane er at det er relativt få deltakarar med (<30). Alle studiane utfører eit RCS-design som gjer at ein deler deltakarane i to grupper og dermed får få personar å teste på. Eit anna moment ved val av deltakarar er at alle studiane gjennomfører protokollen på homogene grupper. Dette er ikkje ein direkte svakhet, men det påverkar generaliserbarheten til studiane. Når @almquist2022 gjennomfører studien på trena syklistar kan ein ikkje direkte forvente det samen resultatet på elite-utøvarar og i tillegg må ein stille spørsmålet om det er relevant for andre idrettar, sjølv om ein er på same nivå. 

Ein anna svakhet er at treningsintervensjonen blir gjennomført over eit for kort tidsrom. @breil2010, @rønnestad2016 & @rønnestad2014a gjennomfører berre ein treningsintervensjon (<4 veker), noko som kan skape usikkerhet om treningsresponsen er noko ein kan stimulere fleire gonger eller om det er eit eingangsverktøy. @almquist2022 og @rønnestad2014b gjennomfører fleire intervensjonar, dette gjev ein større trygghet i om det er repeterbart eller om det er noko som ein berre kan stimulere ein gong. I tillegg så er treningsintervensjonen på desse berre 12 veker og gjev ikkje svar på om ein utøvar skal bruke BP gjennom eit heilt år i forkant av ein viktig konkurranse, eller om det er noko ein nyttar seg av dei siste 4 vekene i forkant av konkurransen som eit siste løft.

@rønnestad2018 gjennomførte ein studie på korleis ein enkel person respondera på BP-trening over 58 veker. Treningsprogrammet inneheldt periodar med LIT, MIT og HIT i ein BP-modell. Resultatet var ein signifikant auke i VO$_{2maks}$ frå 76 til 87. Sjølv om svakheitene med ein slik studie er openberre, med berre ein deltakar og ingen kontrollgruppe, så er dette ein god modell for korleis ein kan gjennomføre lengre studie om korleis BP stimulera VO$_{2maks}$. Inkludera man fleire deltakarar kan man skilje mellom nivå på deltakarane, gjerne i forskjellige grupper, i tillegg til å inkludere ein kontrollgruppe. Dette vil hjelpe stort med å få gode statistiske svar, men også representative svar for den gruppa ein testar BP på.

For framtidige studie som skal sjå på effekten BP har på VO$_{2maks}$ i forhold til TP så bør ein sjå på spørsmålet i eit lengre perspektiv. Tidsrommet bør vere større enn 16 veker og inkludere fleire testar undervegs i treningsintervensjonen for å sjå korleis VO$_{2maks}$ endra seg gjennom ein slik lang periode. I ein slik studie vil eit RCT-studiedesign vere å føretrekkje på grunn av at ein nettopp ser på korleis utviklinga er i dei forskjellige treningsstrukturane over ein lengre periode. Eit mindre viktig poeng, men som bør inkluderast, er at mesteparten av øktene bør gjennomførast med ein testleiar til stades. Dette vil sjølvsagt vere veldig utfordrande når studien er så lang, men ein kan nytte same metode som @almquist2022 med at utøvarane hadde moglegheita til å gjennomføre alle HIT-øktene med testleiar til stades, men det var ikkje eit krav. Dette vil sjølvsagt vere utfordrande med tanke på ressursbruk, men det vil gje veldig gode svar på korleis treningsstruktur påverkar VO$_{2maks}$ over tid.
