project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Kandidatnummer 401"
  date: "2023-11-15"
  chapters:
    - index.qmd
    - 01-Arbeidskrav1.qmd
    - 02-Vitenskapsfilosofi.qmd
    - 03-Labrapport.qmd
    - 04-Studiedesign.qmd
    - 05-Repetertemålingar.qmd
    - references.qmd

bibliography: resources/bib-final.bib

crossref: 
  fig-title: "**Figur**"
  fig-prefix: "Figur"
  tbl-title: "Tabell"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



